FROM node:18-alpine AS builder
WORKDIR /app
COPY app/package*.json ./
RUN npm install
COPY app/ .

FROM node:18-alpine
WORKDIR /app
RUN addgroup -S nodejs && adduser -S nodejs -G nodejs
USER nodejs
COPY --from=builder /app .
EXPOSE 3000
CMD ["node", "src/app.js"]